src/Entity/Bien.php
<?php

namespace App\Entity;

use App\Repository\BienRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BienRepository::class)]
class Bien
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 1)]
    private ?string $Type_Bien = null;

    #[ORM\Column(length: 255)]
    private ?string $Titre_Bien = null;

    #[ORM\Column]
    private ?int $Surface_Bien = null;

    #[ORM\Column]
    private ?float $Prix_Bien = null;

    #[ORM\Column(length: 255)]
    private ?string $Localisation_Bien = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $Description_Bien = null;

    #[ORM\ManyToOne(inversedBy: 'id_Bien')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Categorie $id_Cat = null;

    #[ORM\ManyToMany(targetEntity: Favori::class, mappedBy: 'Numero_Bien')]
    private Collection $id_Fav;

    public function __construct()
    {
        $this->id_Fav = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTypeBien(): ?string
    {
        return $this->Type_Bien;
    }

    public function setTypeBien(string $Type_Bien): self
    {
        $this->Type_Bien = $Type_Bien;

        return $this;
    }

    public function getTitreBien(): ?string
    {
        return $this->Titre_Bien;
    }

    public function setTitreBien(string $Titre_Bien): self
    {
        $this->Titre_Bien = $Titre_Bien;

        return $this;
    }

    public function getSurfaceBien(): ?int
    {
        return $this->Surface_Bien;
    }

    public function setSurfaceBien(int $Surface_Bien): self
    {
        $this->Surface_Bien = $Surface_Bien;

        return $this;
    }

    public function getPrixBien(): ?float
    {
        return $this->Prix_Bien;
    }

    public function setPrixBien(float $Prix_Bien): self
    {
        $this->Prix_Bien = $Prix_Bien;

        return $this;
    }

    public function getLocalisationBien(): ?string
    {
        return $this->Localisation_Bien;
    }

    public function setLocalisationBien(string $Localisation_Bien): self
    {
        $this->Localisation_Bien = $Localisation_Bien;

        return $this;
    }

    public function getDescriptionBien(): ?string
    {
        return $this->Description_Bien;
    }

    public function setDescriptionBien(?string $Description_Bien): self
    {
        $this->Description_Bien = $Description_Bien;

        return $this;
    }

    public function getIdCat(): ?Categorie
    {
        return $this->id_Cat;
    }

    public function setIdCat(?Categorie $id_Cat): self
    {
        $this->id_Cat = $id_Cat;

        return $this;
    }

    /**
     * @return Collection<int, Favori>
     */
    public function getIdFav(): Collection
    {
        return $this->id_Fav;
    }

    public function addIdFav(Favori $idFav): self
    {
        if (!$this->id_Fav->contains($idFav)) {
            $this->id_Fav->add($idFav);
            $idFav->addNumeroBien($this);
        }

        return $this;
    }

    public function removeIdFav(Favori $idFav): self
    {
        if ($this->id_Fav->removeElement($idFav)) {
            $idFav->removeNumeroBien($this);
        }

        return $this;
    }
}

src/Controller/Admin/AdminBienController.php
<?php
namespace App\Controller\Admin;

use App\Entity\Bien;
use App\Form\BienType;
use App\Repository\BienRepository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/bien", name="admin.bien")
 * @package App\Controller\Admin
 */
#[Route(path: '/admin/bien', name: 'admin.bien')]
class AdminBienController extends AbstractController
{
    /**
     * @var BienRepository
     */
    private BienRepository $repository;

     /**
     * @var EntityManagerInterface
     */
    private EntityManagerInterface $em;

    public function __construct(BienRepository $repository, EntityManagerInterface $em)
    {
        $this->repository = $repository;
        $this->em = $em;
    }


    #[Route(path: '/admin', name: 'home')]
    public function index(BienRepository $bienRepo)
    {
        return $this->render('admin/bien/index.html.twig', [
            'bien' => $bienRepo->findAll()
        ]);
    }


    #[Route(path: 'admin/ajout', name: 'admin.bien.ajout')]
    public function ajoutBien(Request $request)
    {
        $bien = new Bien;

        $form = $this->createForm(BienType::class, $bien);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $em = $this->getDoctrine()->getManager();
            $em->persist($bien);
            $em->flush();

            return $this->redirectToRoute('admin.bien.index');
        }

        return $this->render('admin/bien/ajout.html.twig', [
            'form' => $form->createView()
        ]);
    }

    #[Route(path: 'admin/modifier/{id}', name: 'admin.bien.modifier')]
    public function ModifCategorie(Bien $bien, Request $request)
    {
        $form = $this->createForm(BienType::class, $bien);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $em = $this->getDoctrine()->getManager();
            $em->persist($bien);
            $em->flush();

            return $this->redirectToRoute('admin.bien.index');
        }

        return $this->render('admin/bien/ajout.html.twig', [
            'form' => $form->createView()
        ]);
    }
}

src/Controller/AdminBiensController.php
<?php

namespace App\Controller;

use App\Entity\Biens;
use App\Form\BiensType;
use App\Repository\BiensRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin/biens')]
class AdminBiensController extends AbstractController
{
    #[Route('/', name: 'app_admin_biens_index', methods: ['GET'])]
    //Objectif : afficher tous les biens de la bdd
    public function index(BiensRepository $biensRepository): Response
    {
        //Retourne la vue 'admin_biens/index.html.twig'
        return $this->render('admin_biens/index.html.twig', [
            //Récupérer tous les biens stockés dans la bdd
            'biens' => $biensRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_admin_biens_new', methods: ['GET', 'POST'])]
    public function new(Request $request, BiensRepository $biensRepository): Response
    {
        //Créer un nouvel objet bien Biens et le stocker dans $bien
        $bien = new Biens();

        //Créer un formulaire avec la classe BiensType et $bien, et gère une requête en utilisant le formulaire
        $form = $this->createForm(BiensType::class, $bien);
        $form->handleRequest($request);

        //Si le formulaire soumis est valide appeler la méthode save(BiensRepository) avec $bien en tant qu'argument et true en deuxième argument
        if ($form->isSubmitted() && $form->isValid()) {
            $biensRepository->save($bien, true);

            return $this->redirectToRoute('app_admin_biens_index', [], Response::HTTP_SEE_OTHER);
        }

        //Si le formulaire n'est pas soumis ou pas valide retourner la vue 'admin_bien' avec les variables $bien et $form.
        return $this->renderForm('admin_biens/new.html.twig', [
            'bien' => $bien,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_admin_biens_show', methods: ['GET'])]
    public function show(Biens $bien): Response
    {
        //Retourne la vue 'admin_biens/show.html.twig' avec $bien comme argument
        return $this->render('admin_biens/show.html.twig', [
            'bien' => $bien,
        ]);
    }

    //Arguments : requête, objet de Biens et objet de la classe BiensRepository
    #[Route('/{id}/edit', name: 'app_admin_biens_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Biens $bien, BiensRepository $biensRepository): Response
    {
        //Créer un formulaire de la classe BiensType avec l'objet Biens passé en argument,
        // puis gérer la requête HTTP en utilisant ce formulaire
        $form = $this->createForm(BiensType::class, $bien);
        $form->handleRequest($request);

        //Si le formulaire est soumis et valide, la méthode save de BiensRepository est appelée avec
        // Biens et true
        if ($form->isSubmitted() && $form->isValid()) {
            $biensRepository->save($bien, true);

            //Retourne la vue
            return $this->redirectToRoute('app_admin_biens_index', [], Response::HTTP_SEE_OTHER);
        }

        //Sinon (le formulaire n'est pas soumis ou pas valide) retourner la vue edit avec les variables $bien et $form.
        return $this->renderForm('admin_biens/edit.html.twig', [
            'bien' => $bien,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_admin_biens_delete', methods: ['POST'])]
    //Vérifie si le CSRF soumis avec la requête est valide.
    public function delete(Request $request, Biens $bien, BiensRepository $biensRepository): Response
    {
        //S'il est valide appeler la méthode remove de BiensRepository avec l'objet Biens et true
        if ($this->isCsrfTokenValid('delete'.$bien->getId(), $request->request->get('_token'))) {
            $biensRepository->remove($bien, true);
        }

        //Rediriger vers la route indiquée
        return $this->redirectToRoute('app_admin_biens_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/admin_biens/_delete_form.html.twig
<form method="post" action="{{ path('app_admin_biens_delete', {'id': bien.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ bien.id) }}">
    <button class="btn">Delete</button>
</form>

templates/admin_biens/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/admin_biens/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Biens{% endblock %}

{% block body %}
    <h1>Edit Biens</h1>

    {{ include('admin_biens/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_admin_biens_index') }}">back to list</a>

    {{ include('admin_biens/_delete_form.html.twig') }}
{% endblock %}

templates/admin_biens/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Biens index{% endblock %}

{% block body %}
    <h1>Biens index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Type_bien</th>
                <th>Titre_bien</th>
                <th>Surface_bien</th>
                <th>Prix_bien</th>
                <th>Localisation_bien</th>
                <th>Description_bien</th>
                <th>Image</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for bien in biens %}
            <tr>
                <td>{{ bien.id }}</td>
                <td>{{ bien.typeBien }}</td>
                <td>{{ bien.titreBien }}</td>
                <td>{{ bien.surfaceBien }}</td>
                <td>{{ bien.prixBien }}</td>
                <td>{{ bien.localisationBien }}</td>
                <td>{{ bien.descriptionBien }}</td>
                <td>{{ bien.image }}</td>
                <td>
                    <a href="{{ path('app_admin_biens_show', {'id': bien.id}) }}">show</a>
                    <a href="{{ path('app_admin_biens_edit', {'id': bien.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_admin_biens_new') }}">Create new</a>
{% endblock %}

templates/admin_biens/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Biens{% endblock %}

{% block body %}
    <h1>Create new Biens</h1>

    {{ include('admin_biens/_form.html.twig') }}
    <a href="{{ path('app_admin_biens_index') }}">back to list</a>
{% endblock %}

templates/admin_biens/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Biens{% endblock %}

{% block body %}
    <h1>Biens</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ bien.id }}</td>
            </tr>
            <tr>
                <th>Type_bien</th>
                <td>{{ bien.typeBien }}</td>
            </tr>
            <tr>
                <th>Titre_bien</th>
                <td>{{ bien.titreBien }}</td>
            </tr>
            <tr>
                <th>Surface_bien</th>
                <td>{{ bien.surfaceBien }}</td>
            </tr>
            <tr>
                <th>Prix_bien</th>
                <td>{{ bien.prixBien }}</td>
            </tr>
            <tr>
                <th>Localisation_bien</th>
                <td>{{ bien.localisationBien }}</td>
            </tr>
            <tr>
                <th>Description_bien</th>
                <td>{{ bien.descriptionBien }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ bien.image }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_admin_biens_index') }}">back to list</a>

    <a href="{{ path('app_admin_biens_edit', {'id': bien.id}) }}">edit</a>

    {{ include('admin_biens/_delete_form.html.twig') }}
{% endblock %}